name: "Bug Report"
description: "Report an issue with the AUR package of Carch."
title: "[Bug]: "
labels: ["Bug", "Aur"]
assignees:
  - harilvfs
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue with the AUR package of Carch. Please fill out the details below.
  
  - type: input
    id: package_version
    attributes:
      label: "AUR Package Version"
      description: "Which version of the AUR package are you using? (Check with `pacman -Qi carch` or `paru -Qi carch`.)"
      placeholder: "e.g., 1.2.3-1"
    validations:
      required: true
  
  - type: textarea
    id: issue_description
    attributes:
      label: "Issue Description"
      description: "Provide a clear and concise description of the problem."
      placeholder: "What happened? What did you expect to happen?"
    validations:
      required: true
  
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "List the steps needed to reproduce the issue."
      placeholder: "1. Run `yay -S carch`\n2. Execute `carch`\n3. See the error"
    validations:
      required: true

  - type: textarea
    id: logs_and_output
    attributes:
      label: "Error Logs or Output"
      description: "Paste any relevant error messages or logs. Use triple backticks (```) for formatting."
      render: shell
    validations:
      required: false

  - type: dropdown
    id: installation_method
    attributes:
      label: "Installation Method"
      description: "How did you install the package?"
      options:
        - "paru"
        - "yay"
        - "makepkg manually"
        - "Other (specify below)"
    validations:
      required: true
  
  - type: input
    id: installation_method_other
    attributes:
      label: "Other Installation Method"
      description: "If you selected 'Other' above, please specify the installation method."
    validations:
      required: false
  
  - type: dropdown
    id: system_info
    attributes:
      label: "Operating System"
      description: "Select your operating system."
      options:
        - "Arch Linux"
        - "Garuda Linux"
        - "CachyOS"
        - "Other (specify below)"
    validations:
      required: true
  
  - type: input
    id: system_info_other
    attributes:
      label: "Other Operating System"
      description: "If you selected 'Other' above, please specify your operating system."
    validations:
      required: false
  
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Any other details that might help us debug the issue."
    validations:
      required: false

