name: "Feature Request"
description: "Suggest an enhancement for the AUR package of Carch."
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - harilvfs
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an enhancement for the AUR package of Carch. Please provide the details below.

  - type: input
    id: package_version
    attributes:
      label: "AUR Package Version"
      description: "Which version of the AUR package are you using? (Check with `pacman -Qi carch` or `paru -Qi carch`.)"
      placeholder: "e.g., 1.2.3-1"
    validations:
      required: true
  
  - type: textarea
    id: enhancement_description
    attributes:
      label: "Enhancement Description"
      description: "Describe the enhancement you would like to see in the PKGBUILD."
      placeholder: "What improvement do you suggest? Why is it needed?"
    validations:
      required: true
  
  - type: textarea
    id: benefits
    attributes:
      label: "Benefits"
      description: "Explain how this enhancement would improve the AUR package."
      placeholder: "What are the advantages of this change?"
    validations:
      required: true
  
  - type: textarea
    id: implementation_suggestion
    attributes:
      label: "Implementation Suggestion"
      description: "If you have an idea on how to implement this, please describe it."
      placeholder: "Suggest changes to the PKGBUILD or related files."
    validations:
      required: false
  
  - type: dropdown
    id: system_info
    attributes:
      label: "Operating System"
      description: "Select your operating system."
      options:
        - "Arch Linux"
        - "Garuda Linux"
        - "CachyOS"
        - "Other (specify below)"
    validations:
      required: true
  
  - type: input
    id: system_info_other
    attributes:
      label: "Other Operating System"
      description: "If you selected 'Other' above, please specify your operating system."
    validations:
      required: false
  
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Any other details or links related to this request."
    validations:
      required: false

