name: 'Update Carch Submodule'

on:
  push:
    paths:
      - 'carch-x/**'  
  workflow_dispatch:  

permissions:
  contents: write  
  actions: read  

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout documentation repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  

      - name: Set Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Initialize and update submodules
        run: |
          git submodule init
          git submodule update

      - name: Pull latest changes for submodule
        run: |
          cd carch
          git fetch --all
          git checkout main  
          git pull origin main  

      - name: Commit and push changes to the docs repository
        run: |
          git add carch
          git commit -m "Update carch submodule"
          git push origin main  
